// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8SsIXTZNld9e0zKv-gd_LMvLzB4TTIzE',
    appId: '1:332246856773:web:22f62dd4d8c6cf8d575f2c',
    messagingSenderId: '332246856773',
    projectId: 'movie-3ed9e',
    authDomain: 'movie-3ed9e.firebaseapp.com',
    storageBucket: 'movie-3ed9e.appspot.com',
    measurementId: 'G-04WMEWXXSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSI_PfE7PH3A2zJalvSZXzxq5bAP1lD0',
    appId: '1:332246856773:android:d371102c73d932fd575f2c',
    messagingSenderId: '332246856773',
    projectId: 'movie-3ed9e',
    storageBucket: 'movie-3ed9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnMMgtrU60A8kOObUdQr8QC1ZN9lUBshA',
    appId: '1:332246856773:ios:da1c2a4d0c704987575f2c',
    messagingSenderId: '332246856773',
    projectId: 'movie-3ed9e',
    storageBucket: 'movie-3ed9e.appspot.com',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnMMgtrU60A8kOObUdQr8QC1ZN9lUBshA',
    appId: '1:332246856773:ios:a131405b471e8cf2575f2c',
    messagingSenderId: '332246856773',
    projectId: 'movie-3ed9e',
    storageBucket: 'movie-3ed9e.appspot.com',
    iosBundleId: 'com.example.movieapp.RunnerTests',
  );
}
